### ISSUE TITLE
how to port it to AFL's instrumentation mode ?

### ISSUE THREAD

**Issue by ricardo-kcc** [JackGrence/FuzzInspector#1]
hello, @JackGrence . the tools seems cool. And I want to use it under vanilla AFL, but it lack of some tutorials in detail. So could you provide help me some advice ? Thanks.

**Comment by JackGrence** [comment]
Hi @Ricardo-609, you can checkout my forked AFLplusplus repository. There are some commit that make the fuzzinspector communicate with AFLplusplus. I think it is the same way to port to AFL.
Hope it is helpful:
https://github.com/JackGrence/AFLplusplus/commits/fuzzinspector

**Comment by ricardo-kcc** [comment]
Thanks. @JackGrence . it has  paper about this tools ?

**Comment by JackGrence** [comment]
The public paper was written in Chinese only.
https://etd.lib.nctu.edu.tw/cgi-bin/gs32/tugsweb.cgi?o=dnctucdr&s=id=%22GT070866002%22.&searchmode=basic#XXXX

**Comment by ricardo-kcc** [comment]
Thanks!
